#!/usr/bin/env bash
# Build the cold-boot variants, each as a complete servable directory, so a measurement harness can
# point at them one after another and see only the intended difference.
#
# Variants (each still CONFORMANT — a face is only ever demoted from "compiled in" to "fetched as
# data", never removed from the set of faces the reader can use):
#   A  both reader faces embedded   — baseline
#   B  RIDIBatang externalized      — our extra face, absent from the reference entirely
#   C  both externalized            — the core module carries no reader font at all, so only the
#                                     engine is compiled and the fonts arrive as data beside it
#
# Pretendard is not a variant: it is deleted (KO_EMBED_PRETENDARD no longer exists). It was never
# drawn when reading — the reference's `setFallbackFont(UI_FONT_ID)` is font-ID-level and KoPub is
# always registered, and the only glyph-level fallback is `setGlyphFallback(SYSTEM_FONT_ID, ...)`,
# an SD-system-font device path. See docs/ko-font-payload-measurement.md.
#
# Each variant dir is web/ + the variant's engine + the faces that engine does not embed, so the
# page, worker and CSS are identical across variants; only the module and the data assets differ.
#
# usage: cold_boot_variants.sh [A|B|C|D ...]     (default: all)
set -uo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"
OUT="${OUT:-/tmp/coldboot}"
WANT="${*:-A B C}"
JOBS="${JOBS:-8}"
mkdir -p "$OUT"

# face -> EPD2 blob, generated by build/export_external_font (host build, not the wasm). Generated
# on demand: the blobs are derived artifacts, so the repo tracks the generator rather than 5 MB of
# output that the default (all-embedded) build would ship to every visitor for nothing.
#
# No associative arrays here on purpose: /bin/bash on macOS is 3.2, where `declare -A` does not exist
# and `NAME=( [kopub]=x )` is parsed as an ARITHMETIC subscript, failing with "kopub: unbound
# variable" before anything is built. A case statement is portable and just as clear.
blob_for() {
  case "$1" in
    kopub)      echo /tmp/ab/kopub_14.epd2 ;;
    ridibatang) echo /tmp/ab/ridi_14.epd2 ;;
    *)          echo "" ;;
  esac
}
# the exporter's face argument is the face name itself
for _face in kopub ridibatang; do
  _blob="$(blob_for "$_face")"
  if [ ! -f "$_blob" ]; then
    [ -x build/export_external_font ] || { echo "need build/export_external_font (cmake --build build)"; exit 1; }
    echo "== exporting $_face -> $_blob =="
    build/export_external_font "$_blob" "$_face" >/dev/null || { echo "  export FAILED"; exit 1; }
  fi
done

for v in $WANT; do
  case "$v" in
    A) RIDI=ON;  KOPUB=ON  ;;
    B) RIDI=OFF; KOPUB=ON  ;;
    C) RIDI=OFF; KOPUB=OFF ;;
    *) echo "unknown variant $v (A|B|C)"; exit 2 ;;
  esac
  bdir="$OUT/build-$v"
  vdir="$OUT/site-$v"
  if [ ! -f "$bdir/ko_xtch_wasm.wasm" ]; then
    echo "== building variant $v (RIDI=$RIDI KOPUB=$KOPUB) =="
    emcmake cmake -S . -B "$bdir" -DCMAKE_BUILD_TYPE=Release \
      -DKO_EMBED_RIDI=$RIDI -DKO_EMBED_KOPUB=$KOPUB \
      >"$OUT/$v.cmake.log" 2>&1 || { echo "  cmake FAILED"; tail -5 "$OUT/$v.cmake.log"; continue; }
    cmake --build "$bdir" -j"$JOBS" --target ko_xtch_wasm >"$OUT/$v.build.log" 2>&1 \
      || { echo "  build FAILED"; tail -5 "$OUT/$v.build.log"; continue; }
  fi

  # servable dir: everything web/ has (page, worker, css, fixtures) plus this variant's engine and
  # the blobs for the faces it does not embed
  rm -rf "$vdir"; mkdir -p "$vdir"
  rsync -a --exclude 'ko_xtch_wasm.wasm' --exclude 'ko_xtch_wasm.js' \
        --exclude 'ko_build_info.js' \
        --exclude 'assets.js' --exclude 'assets.json' --exclude 'demo.epub' \
        --exclude '*.epd2' \
        "$REPO_ROOT/web"/ "$vdir"/
  cp "$bdir/ko_xtch_wasm.wasm" "$bdir/ko_xtch_wasm.js" "$vdir"/
  cp "$bdir/ko_build_info.js" "$vdir"/ 2>/dev/null || echo "  WARN: no ko_build_info.js in $bdir"
  # ship exactly the faces this build does not carry
  [ "$RIDI"  = OFF ] && cp "$(blob_for ridibatang)" "$vdir/ridibatang_14.epd2"
  [ "$KOPUB" = OFF ] && cp "$(blob_for kopub)"      "$vdir/kopub_14.epd2"

  raw=$(stat -f%z "$vdir/ko_xtch_wasm.wasm")
  br=$(brotli -q 11 -c "$vdir/ko_xtch_wasm.wasm" | wc -c | tr -d ' ')
  assets=0
  for b in "$vdir"/*.epd2; do [ -f "$b" ] && assets=$((assets + $(brotli -q 11 -c "$b" | wc -c | tr -d ' '))); done
  printf '%-3s wasm raw %9s brotli %9s + faces brotli %8s = %8s total\n' \
    "$v" "$raw" "$br" "$assets" "$((br + assets))"
done
