#!/usr/bin/env python3
"""Print the divergence audit straight out of the pin, as markdown.

The table in docs/ko-oracle-conformance.md is generated by this, so the document cannot
quietly disagree with the pin it claims to describe. If the numbers here and the numbers in
the doc ever differ, the doc is wrong.

usage: oracle_report.py [--pin PATH]
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(HERE))
DEFAULT_PIN = os.path.join(REPO_ROOT, 'oracle', 'crosspoint-ko.pin.json')


def main():
    pin_path = sys.argv[sys.argv.index('--pin') + 1] if '--pin' in sys.argv else DEFAULT_PIN
    pin = json.load(open(pin_path, encoding='utf-8'))
    c = pin['counts']
    print(f"Reference: `{pin['repo']}` branch `{pin['branch']}` at `{pin['commit']}`")
    print()
    print(f"Engine files under {', '.join('`' + s + '`' for s in pin['engine_scope'])}: "
          f"**{c['reference_engine_files']}**")
    print()
    print('| | count | how it is checked |')
    print('|---|---|---|')
    print(f"| byte-identical to the reference | {c['identical']} | Git blob hash |")
    print(f"| divergent (audited) | {c['divergent']} | per-function bodies + line survival |")
    print(f"| absent from the port | {c['missing_from_port']} | headers only, listed |")
    print()
    print('### Divergent files')
    print()
    print('| file | kind | lines +/− | functions changed | port-only | reference-only | layout-critical |')
    print('|---|---|---|---|---|---|---|')
    for path, e in sorted(pin['divergent'].items()):
        lc = e.get('layout_critical_checked')
        if lc:
            lc_txt = f"{len(e['layout_critical_identical'])}/{len(lc)} identical"
        else:
            lc_txt = '—'
        print(f"| `{path}` | {e['divergence_kind']} | +{e['added_lines']}/−{e['removed_lines']} | "
              f"{len(e['changed_functions'])} | {len(e['only_in_port'])} | "
              f"{len(e['only_in_reference'])} | {lc_txt} |")
    print()
    print('### Layout-critical functions required to be identical')
    print()
    for path, names in pin['layout_critical'].items():
        print(f'`{path}`:')
        print()
        for n in names:
            print(f'- `{n}()`')
    return 0


if __name__ == '__main__':
    sys.exit(main())
