// ko.worker.js — owns the CrossPoint-KO WASM module. Receives commands:
//   {id, cmd:'load', epub:ArrayBuffer}
//   {id, cmd:'spec', spec:{...}}
//   {id, cmd:'build', spine}
//   {id, cmd:'render', page, spine}   (render one page, rebuild spine if needed)
//   {id, cmd:'pageCount'}             → current spine page count
// Replies {id, ok, ...}. ImageData buffers are transferable copies.
/* eslint-env worker */
// §26: generated artifacts are content-addressed (name.<hash8>.ext). The manifest is imported
// under this worker's own ?v= cache-bust, so it is always as fresh as the worker.
//
// The import MUST be guarded: assets.js only exists in dist/ (fingerprint_assets.py writes it), so
// when web/ is served directly — `python3 server.py`, which is the documented dev path — a bare
// importScripts() throws here and kills the worker before any of the plain-name fallbacks below can
// run. On failure __ASSETS stays undefined and every asset() call degrades to the plain name.
try {
  importScripts('assets.js' + self.location.search);
} catch (_) {
  self.__ASSETS = {};
}
const ASSETS = self.__ASSETS || {};
const asset = (name) => ASSETS[name] || name;

// Which faces this module carries. Generated by CMake from the same switches that decide what is
// compiled in, staged next to the module, and reached through the asset manifest — so a
// content-addressed engine can never be paired with a different build's declaration.
// Guarded for the same reason assets.js is: a bare web/ checkout may not have it.
try {
  importScripts(asset('ko_build_info.js') + self.location.search);
} catch (_) { /* no build info: see embeddedFaces() — it does not guess in a packaged build */ }

// cache-busted like the two declaration files above, and for the same reason: the engine glue carries
// the export wrappers, so a stale glue next to a fresh .wasm is a module whose new functions do not
// exist — which is exactly how this was found ("api._ko_start_spine is not a function" with the rebuilt
// module sitting on disk). The name is content-addressed in dist/, so the query is only a dev-loop
// cache-buster there.
importScripts(asset('ko_xtch_wasm.js') + self.location.search);   // defines createKoEngine (MODULARIZE)

let Module = null;         // wasm module instance
let api = null;            // C-export surface
let spineCount = 0;
// Composed-frame cache: a navigation that repeats a (spine, page, mode, spec, font) tuple
// reuses the frame instead of re-rendering and re-composing. Bounded by bytes because a frame
// is 1.5 MB (480*800*4) and the wasm heap is 2 GB - 128 frames is ~192 MB.
// §5: 192 MB of 1.5 MB RGBA frames was excessive — rendering a text page is sub-millisecond, so a
// huge retrospective cache bought little and cost mobile memory. 48 MB still holds a few dozen
// frames (plenty for flipping back and forth) and the next-page prefetch below makes the common
// sequential turn a hit.
const FRAME_CACHE_BUDGET = 48 * 1024 * 1024;
const frameCache = new Map();          // key -> { data: Uint8ClampedArray }, insertion ordered
let frameCacheBytes = 0;
// A new book reuses spine/page numbers, so frames must not survive a load. The generation counter
// is part of every frame key (belt and braces next to the explicit clear).
let bookGen = 0;
const COUNTERS = {
  epdfontLoads: 0, fontApplies: 0, fontSkips: 0, specApplies: 0, layoutApplies: 0,
  renderApplies: 0, builds: 0, renders: 0, framesPosted: 0, cacheHits: 0, prefetches: 0,
  cacheEvictions: 0, warmYields: 0, warmCooldowns: 0, aborts: 0,
};

// §1 of the 1.3 audit: ONE way to stop an export early. Every early return and every throw inside
// exportWholeBook must release the writer's partially accumulated pages, otherwise they stay in the
// wasm heap until the next ko_export_begin(). COUNTERS.aborts makes a missed path visible in stats.
function cancelCurrentExport(total) {
  api._ko_export_abort();
  invalidateSectionTracking();
  COUNTERS.aborts += 1;
  return { cancelled: true, pages: total };
}
function clearFrameCache() {
  frameCache.clear();
  frameCacheBytes = 0;
}

function frameCacheGet(key) {
  const hit = frameCache.get(key);
  if (!hit) return null;
  frameCache.delete(key);              // refresh recency
  frameCache.set(key, hit);
  return hit;
}

// §4 of the 1.1 audit: a frame that is about to be transferred to the main thread MUST be copied
// (the transfer detaches the source), but a prefetch-only frame is never transferred, so the cache
// can take ownership of it instead of paying a second 1.5 MB copy.
function frameCachePut(key, data, takeOwnership) {
  const stored = takeOwnership ? data : new Uint8ClampedArray(data);   // ctor on a typed array copies
  if (frameCache.has(key)) frameCacheBytes -= frameCache.get(key).data.length;
  frameCache.set(key, { data: stored });
  frameCacheBytes += stored.length;
  while (frameCacheBytes > FRAME_CACHE_BUDGET && frameCache.size > 1) {
    const oldest = frameCache.keys().next().value;
    frameCacheBytes -= frameCache.get(oldest).data.length;
    frameCache.delete(oldest);
    COUNTERS.cacheEvictions += 1;
  }
}

let currentSpine = -1;
let currentPages = 0;
let currentSpec = null;
let builtKey = null;   // specKey of the spine currently built in the engine
let builtFontStamp = 0; // fontStamp at last build (font swaps force a rebuild)

const FONT_IDS = {
  ridibatang: -183759873,   // RIDIBATANG_14_FONT_ID (KO build default)
  kopub: -1446433084,       // KOPUB_14_FONT_ID
  custom: -999999,          // CUSTOM_FONT_ID (runtime .epdfont)
};

let customFontBytes = null;   // cached .epdfont bytes, re-applied after book loads
let customFontName = 'custom';
// Monotonic font stamp: bumped on every loadFont/clearFont. Pagination is fixed
// at spine build time, and the worker spec (font: 'custom') does NOT change when
// a different custom face is loaded — without the stamp, render() would skip the
// rebuild and page breaks would stay stale (wrong wraps for a new size/weight).
let fontStamp = 0;

// Background whole-book conversion result (held in worker, pulled on demand).
let warmBytes = null;

// §3 of the 1.1 audit: a completed warm is the whole container in the JS heap — ~195 MB for a
// 2,000-page XTCH. It was only ever cleared by fetchWarm(), so a cancelled warm, a new book and the
// next warm all left their megabytes resident, and two warm results could coexist.
function dropWarmResult() {
  warmBytes = null;
  warmPages = 0;
  warmRaw = 0;
  warmMode = 1;
  warmXtcz = false;
}
let warmPages = 0;
let warmRaw = 0;
let warmMode = 1;
let warmXtcz = false;
let warmToken = 0;
let warmRunning = false;

// §1/§2 of the 1.2 audit: the worker yields between export spines, so another message can run while a
// foreground export is mid-flight. A spec change there would produce ONE FILE containing TWO layouts
// (and a book or font swap would be worse). The UI disable is a courtesy; this flag is the invariant.
const MUTATING_COMMANDS = ['spec', 'load', 'loadFile', 'loadFont', 'clearFont', 'convertFont'];
let foregroundExportRunning = false;

// §2 of the 1.3 audit: a background warm shares the engine and the C export buffer, so anything that
// replaces engine state must stop it and WAIT until it has actually stopped. The previous version
// gave up after 4000 spins and let the caller mutate anyway — failing OPEN, which is exactly the race
// this exists to prevent. It now awaits a completion promise, so there is no timing assumption at all.
let resolveWarmDone = null;
let warmDone = Promise.resolve();
function beginWarm() {
  warmRunning = true;
  warmDone = new Promise((resolve) => { resolveWarmDone = resolve; });
}
function endWarm() {
  warmRunning = false;
  if (resolveWarmDone) { resolveWarmDone(); resolveWarmDone = null; }
}
async function stopWarmBeforeMutation() {
  if (!warmRunning) return;
  warmToken++;              // ask it to abort at its next yield
  await warmDone;           // and wait for the handler to actually finish
  dropWarmResult();
}

// per-command wall-clock timing (ms) — n = cumulative invocations
let cmdTimes = {};
function tick(cmd) {
  if (!cmdTimes[cmd]) cmdTimes[cmd] = { n: 0 };
  cmdTimes[cmd].t0 = performance.now();
}
function tock(cmd) {
  const e = cmdTimes[cmd];
  if (e) { e.ms = performance.now() - e.t0; e.n += 1; }
}

function defaultSpec() {
  return {
    lineCompression: 1.2,
    paragraphIndent: 0,
    characterWrap: 1,
    paragraphAlignment: 0,   // JUSTIFIED
    extraParagraphSpacing: 1,
    hyphenation: 0,
    embeddedStyle: 1,
    imageRendering: 0,
    textAa: 1,
    imageDither: 2,        // blue noise
    imageToneDepth: 4,     // 2-bit until the app says otherwise
    screenMargin: 5,
    // Reader face. CrossPoint-KO's own default: CrossPointSettings::
    // getReaderFontId() returns hasCustomFont() ? CUSTOM_FONT_ID : KOPUB_14_FONT_ID.
    // RIDIBatang does not exist upstream — it is an XTCKO extra, selectable but
    // never the default, because a different face means different advances and
    // therefore different line breaks.
    font: 'kopub',
  };
}

// ---------------------------------------------------------------------------
// Text-viewport derivation for the EXPORTED FILE — the reference reader's own
// arithmetic (CrossPoint-KO @ release/korean, EpubReaderActivity::render()):
//
//   GfxRenderer::getOrientedViewableTRBL()  →  portrait 9/3/3/3
//   t += screenMargin;  r += screenMargin;  l += screenMargin;
//   b += max(screenMargin, UITheme::getStatusBarHeight());
//   viewport = screen - (l+r, t+b)
//
// getStatusBarHeight() at CrossPointSettings' shipped defaults is
// metrics.statusBarVerticalMargin = 19: the text lane is visible
// (statusBarChapterPageCount / statusBarBookProgressPercentage /
// statusBarTitle=CHAPTER_TITLE / statusBarBattery are all on by default) and
// progressBarMode is HIDE_PROGRESS, so there is no second term. All shipped
// themes use 19 (BaseTheme.h / LyraTheme.h / RoundedRaffTheme.h).
//
// The lane is a RESERVATION, not content. Nothing of the status bar is ever
// written into an exported page — the device composites its own chrome at read
// time (XtcReaderActivity, xtcStatusBarMode default XTC_STATUS_BAR_HIDE) — but
// reserving it is what puts the lines on the same y the reader would use, and
// that is the whole point of following this engine. Texts paginate identically
// whether or not the device has a status bar switched on, because the
// reservation is a constant here, not a function of a UI setting.
//
// Net: default margins 14/8/22/8 → viewport 464x764, matching the reference
// reader's live layout.
// ---------------------------------------------------------------------------
const VIEWABLE_MARGIN = { top: 9, right: 3, bottom: 3, left: 3 };  // GfxRenderer::VIEWABLE_MARGIN_*
const REFERENCE_STATUS_LANE = 19;   // UITheme::getStatusBarHeight() on the shipped defaults
const SCREEN_W = 480;
const SCREEN_H = 800;

function marginsFor(spec) {
  const m = spec.screenMargin;
  return {
    top: VIEWABLE_MARGIN.top + m,
    right: VIEWABLE_MARGIN.right + m,
    left: VIEWABLE_MARGIN.left + m,
    bottom: VIEWABLE_MARGIN.bottom + Math.max(m, REFERENCE_STATUS_LANE),
  };
}

function viewportFor(spec) {
  const mg = marginsFor(spec);
  return { width: SCREEN_W - mg.left - mg.right, height: SCREEN_H - mg.top - mg.bottom, margins: mg };
}

// §3: pagination depends on these fields only. Changing XTC/XTCH, the dither model or text AA
// must NOT repaginate the chapter — those are pixel-only.
const LAYOUT_FIELDS = [
  'lineCompression', 'paragraphAlignment', 'paragraphIndent', 'extraParagraphSpacing',
  'characterWrap', 'hyphenation', 'embeddedStyle', 'screenMargin', 'font', 'imageRendering',
];
const RENDER_FIELDS = ['textAa', 'imageDither', 'imageToneDepth'];
function keyOf(spec, fields) {
  const o = {};
  for (const f of fields) o[f] = (spec || {})[f];
  return JSON.stringify(o);
}
function layoutKey(spec) { return keyOf(spec, LAYOUT_FIELDS); }
function renderKey(spec) { return keyOf(spec, LAYOUT_FIELDS.concat(RENDER_FIELDS)); }
function specKey(spec) { return layoutKey(spec); }   // kept for the spec reply's field name

// §4: interactive work must not queue behind speculative export work.
// lastInteractiveAt / INTERACTIVE_COOLOFF_MS lived here: the warm used to stand aside for 120 ms
// whenever the reader turned a page, because warm and preview shared one engine. The export engine is
// separate, so there is nothing to stand aside for.

// §4 of the 1.4 audit: a 2,000-page XTCH is ~195 MB. Pre-rendering that speculatively and keeping it
// in the JS heap is a bad mobile trade, so a background warm stops once the RAW projection (the writer
// accumulates uncompressed pages even for XTZ4) passes this budget. A user-requested export is never
// capped.


// A macrotask hop that is NOT clamped: browsers clamp nested setTimeout(0) to ~4 ms, which would add
// seconds to a whole-book pass. postMessage to our own port yields just as effectively at ~0.1 ms,
// so a page-turn message can be serviced after every single spine.
const yieldPort = new MessageChannel();
let yieldResolve = null;
yieldPort.port1.onmessage = () => { const r = yieldResolve; yieldResolve = null; if (r) r(); };
function yieldToLoop() {
  return new Promise((res) => { yieldResolve = res; yieldPort.port2.postMessage(0); });
}

function post(id, ok, payload, transfer) {
  self.postMessage(Object.assign({ id, ok }, payload), transfer || []);
}

// ---- font conversion (no local server needed) -----------------------------
// FreeType (tools/ft_wasm.c) + the .epdfont packer (web/epdfont.js), both loaded on
// first use so a page that never picks a custom font pays nothing. Version-pinned like
// the engine: emscripten's glue fetches the .wasm with no query, so without ?v= the edge
// would serve a cached module forever after any rebuild.
const FT_MODULE_VERSION = '42';
let fontConv = null;
let ftVersionString = '';
async function getFontConverter() {
  if (fontConv) return fontConv;
  if (typeof EpdFontConverter === 'undefined') {
    // both hops cache-busted: a stale ft_wasm.js next to a fresh .wasm is the same trap the engine
    // glue taught us, and epdfont.js is versioned against the packer it must match.
    importScripts(asset('ft_wasm.js') + self.location.search, 'epdfont.js?v=' + FT_MODULE_VERSION);
  }
  fontConv = await EpdFontConverter.load({
    factory: createFtConverter({
      locateFile: (p) => asset(p),
    }),
  });
  ftVersionString = fontConv.ftVersion || '';
  return fontConv;
}

// Copy a 48000-byte plane from wasm heap into a JS Uint8Array.
function copyPlane(kind) {
  const ptr = api._ko_plane_ptr(kind);
  const size = api._ko_plane_size(kind);
  if (!ptr || size <= 0) return null;
  return new Uint8Array(api.HEAPU8.buffer.slice(ptr, ptr + size));
}

// Compose the 3 physical (800x480) planes into a logical portrait 480x800
// grayscale image per the device decode contract:
//   value = !ink?white : lsb?dark-grey : msb?light-grey : black
//   logical(x,y) ← physical(phyX=y, phyY=479-x)
const GRAY = [255, 128, 205, 0]; // white, dark-grey, light-grey, black


// 1-bit (XTC / XTG) preview: the file stores ONLY the BW plane — no AA greys.
// Bit 0 = black on the device; this is byte-exactly what addMonoPage() packs.
// The pixels are composed inside the engine now: ko_compose_rgba() fills an engine-owned
// 480x800 RGBA buffer and we wrap it as a ZERO-COPY view. No JS pixel loop exists.
// The buffer can move if wasm memory grows, so the pointer is fetched AFTER composing and
// the view is rebuilt every call. putImageData reads it synchronously, so the view stays valid.
// tick/tock are the worker's existing stage timers; used defensively so this stays valid if
// they are not in scope here.
function _stage(name, fn) {
  const has = typeof tick === 'function' && typeof tock === 'function';
  if (has) tick(name);
  try { return fn(); } finally { if (has) tock(name); }
}

// A view over wasm memory CANNOT be transferred through postMessage - the browser throws
// 'cannot transfer WebAssembly ArrayBuffer', because wasm memory is non-detachable by spec.
// So the frame is copied out into a normal ArrayBuffer here: one native typed-array copy
// (~1.5 MB), not per-pixel work. The engine-side compose and its single 32-bit store per
// pixel are unaffected.
function _frameFromEngine() {
  const src = new Uint8ClampedArray(api.HEAPU8.buffer, api._ko_rgba_ptr(), 480 * 800 * 4);
  const img = new ImageData(480, 800);
  img.data.set(src);
  return img;
}

// 1-bit callers (XTC preview/export) read only the BW plane, so the engine can skip both gray passes.
// Falls back to the plain entry point if this module predates ko_render_page_mode.
function renderPageEngine(page, mono) {
  if (api._ko_render_page_mode) return api._ko_render_page_mode(page, mono ? 1 : 0);
  return api._ko_render_page(page);
}

function composeMono() {
  _stage('compose.mono', () => {
    if (api._ko_compose_rgba(1) !== 0) throw new Error('engine compose failed (mono)');
  });
  return _stage('compose.view', _frameFromEngine);
}

function composePage() {
  _stage('compose.page', () => {
    if (api._ko_compose_rgba(0) !== 0) throw new Error('engine compose failed');
  });
  return _stage('compose.view', _frameFromEngine);
}

// §2 of the 1.5 audit: the size cap used to be checked AFTER _ko_export_spine() had rendered and
// stored a whole spine, so one giant XHTML spine could allocate hundreds of MB before the check ran —
// and Emscripten never returns linear memory, so the high-water mark stayed grown even after the abort.
// Decide from pagination alone, before any encoded page exists. Small books get paginated twice; that
// is deliberate, and measure before caching page counts by layout key.

// §2 + §5 of the 1.1 audit: speculation must never sit in front of the requested frame, and a
// cache HIT must schedule a prefetch too — otherwise a sequential read alternates miss/hit and only
// every other turn is covered.
//
// The reply is posted first; this runs as its own macrotask, so the extra render cannot delay the
// frame the user is waiting for. Every guard is re-checked when the task actually runs: if a warm
// started, the book changed, the spine/page state moved on, or the render key or font stamp changed,
// a frame rendered now would belong to different state — so it is dropped instead of cached.
// §2 of the 1.4 audit: an export result is built with an exact ArrayBuffer.slice(), so its buffer is
// already exactly the payload and can be transferred as-is. Re-slicing it before post() copied the
// whole output a second time — harmless at 674 KB, hundreds of MB on a large export. The fallback only
// exists for a future caller that hands over a subview.
function takeTransferBuffer(u8) {
  if (u8.byteOffset === 0 && u8.byteLength === u8.buffer.byteLength) return u8.buffer;
  return u8.slice().buffer;
}

function schedulePrefetch(spine, page, pages, mono, rk, fStamp, gen) {
  setTimeout(() => {
    if (warmRunning) return;                       // the engine is walking spines
    if (gen !== bookGen) return;                   // different book
    if (spine !== currentSpine || pages !== currentPages) return;
    if (fStamp !== builtFontStamp) return;
    if (rk !== renderKey(currentSpec || {})) return;
    const next = page + 1;
    if (next >= pages) return;
    const nk = gen + ':' + spine + ':' + next + ':' + (mono ? 1 : 0) + ':' + rk + ':' + fStamp;
    if (frameCache.has(nk)) return;
    // Always preceded by a real render of the requested page, so the engine's planes can never be
    // composed as the wrong page here.
    if (renderPageEngine(next, mono) !== 0) return;
    const nextImg = mono ? composeMono() : composePage();
    frameCachePut(nk, nextImg.data, true);         // never transferred → the cache takes ownership
    COUNTERS.prefetches += 1;
  }, 0);
}

// Cold-boot phases, in milliseconds since the worker started. Kept on `self` so a caller can read
// them after the fact, and reported once at the end of init(): "cold boot is slow" is not
// actionable, "glue 12 ms, wasm 1180 ms, init 4 ms" is.
const BOOT = {
  workerStart: typeof performance !== 'undefined' ? performance.now() : 0,
  glueReady: 0,
  factoryStart: 0,
  wasmReady: 0,
  engineReady: 0,
};

// ---- external reader faces ---------------------------------------------------
//
// A build can leave a built-in face OUT of the module (KO_EMBED_<FACE>=OFF) and ship it as an EPD2
// data asset instead. The worker reads the build's own declaration (ko_build_info.js, generated by
// CMake from the same switches that decide what is compiled in) and fetches the missing faces IN
// PARALLEL with the module's own fetch/compile. That parallelism is the entire reason this can win
// on cold boot: only the core module needs compilation, and the font is just data arriving beside it.
//
// Registration must complete before any render, so init() awaits it — but the *fetch* starts before
// the factory await, which is what makes it parallel rather than sequential.
const FACE_IDS = {
  kopub: -1446433084,        // KOPUB_14_FONT_ID    (must match src/fontIds.h)
  ridibatang: -183759873,    // RIDIBATANG_14_FONT_ID
};
const FACE_ASSETS = {
  kopub: 'kopub_14.epd2',
  ridibatang: 'ridibatang_14.epd2',
};
const FACE_NAMES = Object.keys(FACE_IDS);
// Whether the build actually told us what it carries. This matters more than it looks: the previous
// fallback ("no build info → assume both faces are embedded") is convenient when serving raw web/
// and dangerous in a package, because a packaged build missing its declaration would silently skip
// the fetch and render with no font at all. So the assumption is only made when there is no manifest
// either, i.e. in a bare source checkout, and the packaged case is asserted by build_dist.sh.
const hasBuildInfo = Array.isArray(self.KO_EMBEDDED_FACES);
const PACKAGED = typeof self.__ASSETS === 'object' && self.__ASSETS !== null &&
                 Object.keys(self.__ASSETS).length > 0;
const embeddedFaces = () => {
  if (hasBuildInfo) return self.KO_EMBEDDED_FACES;
  if (PACKAGED) {
    throw new Error('packaged build without ko_build_info.js: cannot tell which faces the engine '
                    + 'carries. This package is broken; rebuild it (scripts/build_dist.sh asserts it).');
  }
  return FACE_NAMES;      // bare web/ checkout: nothing is externalized, nothing to fetch
};
const faceNameForFontId = (id) => FACE_NAMES.find((n) => FACE_IDS[n] === id) || null;

// The face the default spec selects. It is prefetched at boot, in parallel with the module, because
// the first render needs it. Every OTHER non-embedded face is fetched on demand, the first time it is
// selected — a reader who never picks RIDIBatang never downloads its 236 KB of brotli.
const DEFAULT_FACE = 'kopub';

// Fetch the EPD2 bytes for a face. No engine involved, so this can run while the module is still
// being fetched and compiled — that parallelism is the point.
//
// Retried, because an externalized face is on the BOOT-CRITICAL path: the default reader face is a
// separate request from the module now, so the chance of at least one critical fetch failing is
// strictly higher than when the font travelled inside the module, and the failure mode is a reader
// with no font at all. Three attempts with backoff, and `cache: 'reload'` on the retries so a
// poisoned or half-written cache entry cannot make every attempt fail the same way. A hard failure
// still throws — a wrong or missing face must never be rendered around.
async function fetchFaceBytes(name) {
  const url = asset(FACE_ASSETS[name]);
  let lastErr = null;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const r = await fetch(url, attempt === 0 ? undefined : { cache: 'reload' });
      if (!r.ok) throw new Error(`face ${name}: HTTP ${r.status} for ${FACE_ASSETS[name]}`);
      return { name, bytes: new Uint8Array(await r.arrayBuffer()) };
    } catch (e) {
      lastErr = e;
      if (attempt < 2) await new Promise((res) => setTimeout(res, 250 * (attempt + 1)));
    }
  }
  throw lastErr;
}

// name -> Promise<boolean>, memoised so a face is fetched and registered at most once even if several
// commands ask for it while the download is still in flight.
const facePromises = new Map();

// Bring a face into the engine on demand. Resolves true when it is available (embedded, or fetched
// and registered), and rejects only if the blob could not be fetched or was rejected by the loader —
// callers must not silently render with a missing face.
function ensureFace(name) {
  if (!name) return Promise.resolve(true);
  if (embeddedFaces().includes(name)) return Promise.resolve(true);
  if (api && api._ko_has_font(FACE_IDS[name])) return Promise.resolve(true);
  if (!facePromises.has(name)) {
    facePromises.set(name, (async () => {
      const fetched = await fetchFaceBytes(name);
      registerFaces([fetched]);
      return true;
    })());
    // a failed load must not poison the cache — the next attempt should retry
    facePromises.get(name).catch(() => facePromises.delete(name));
  }
  return facePromises.get(name);
}

// Copy each fetched blob into the module's heap ONCE and register it. The pointer is deliberately
// never freed: the engine's EpdFontData points straight into this allocation for the lifetime of the
// engine (see src/external_font_loader.h — the loader copies today, so freeing it would only be
// wrong once that becomes a zero-copy view; either way, ownership stays here).
const facePtrs = [];
function registerFaces(fetched) {
  const results = [];
  for (const { name, bytes } of fetched) {
    const ptr = api._malloc(bytes.length);
    if (!ptr) throw new Error(`face ${name}: malloc(${bytes.length}) failed`);
    api.HEAPU8.set(bytes, ptr);
    const rc = api._ko_load_external_builtin_font(FACE_IDS[name], ptr, bytes.length);
    if (rc !== 0) {
      api._free(ptr);
      throw new Error(`face ${name}: loader rejected the blob (rc=${rc}) ${api.UTF8ToString(api._ko_error())}`);
    }
    facePtrs.push(ptr);
    results.push({ name, bytes: bytes.length });
  }
  return results;
}

async function init() {
  // Emscripten MODULARIZE: ko_xtch_wasm.js defines createKoEngine in scope.
  const factory = self.createKoEngine;
  BOOT.glueReady = performance.now();
  BOOT.factoryStart = performance.now();
  // Start the default face's fetch BEFORE awaiting the module: two independent downloads, and the
  // point is that they overlap. Faces other than the default are left alone — they load on selection.
  const eagerFaces = embeddedFaces().includes(DEFAULT_FACE) ? [] : [DEFAULT_FACE];
  const facesPromise = Promise.all(eagerFaces.map(fetchFaceBytes))
    .catch((e) => { BOOT.faceError = String(e); return []; });
  // Cache-bust the engine binaries: the emscripten glue fetches the .wasm with no version
  // query, so without this the edge serves a previously cached engine indefinitely and no
  // engine change can ever reach a returning browser.
  Module = await factory({ locateFile: (path) => asset(path) });
  api = Module;
  BOOT.wasmReady = performance.now();
  // deterministic viewport: engine computes from margins; init with full logical
  api._ko_init(464, 764); // will be fixed up by ko_set_margins on first spec
  // Register external faces AFTER ko_init, not before: the loader needs the renderer that ko_init
  // creates (`ko_load_external_builtin_font` → "engine not initialised" otherwise) and
  // `ko_has_font` reads the renderer's registry. The parallel part is the FETCH above, which is the
  // part that costs network time; registration is a memcpy.
  const fetched = await facesPromise;
  if (fetched.length) {
    BOOT.facesRegistered = registerFaces(fetched);
    BOOT.facesBytes = BOOT.facesRegistered.reduce((n, f) => n + f.bytes, 0);
  }
  // A face that is neither compiled in nor fetched would render as blank pages, and nothing else in
  // the pipeline would say why. Only the DEFAULT face is a boot requirement: it is needed for the
  // first render. Every other face is fetched on demand by ensureFace(), so its absence here is the
  // expected state, not a degradation — reporting it as one would train people to ignore the message.
  if (!api._ko_has_font(FACE_IDS[DEFAULT_FACE])) {
    throw new Error(`reader face missing: ${DEFAULT_FACE} is neither embedded nor loaded `
                    + `(embedded: ${embeddedFaces().join(', ') || 'none'})`);
  }
  // Faces still absent because they are lazy. Recorded so `bootstats` can state the configuration
  // rather than leave it to be inferred from which assets happen to be on the server.
  BOOT.lazyFaces = FACE_NAMES.filter((f) => !api._ko_has_font(FACE_IDS[f]));
  BOOT.engineReady = performance.now();
  BOOT.phases = {
    glue: +(BOOT.glueReady - BOOT.workerStart).toFixed(1),
    factory: +(BOOT.wasmReady - BOOT.factoryStart).toFixed(1),
    init: +(BOOT.engineReady - BOOT.wasmReady).toFixed(1),
    total: +(BOOT.engineReady - BOOT.workerStart).toFixed(1),
  };
  // Wall clock at "engine ready", so the PAGE can express this relative to its own navigationStart
  // without the two contexts needing a shared timer (a worker's performance.now() has its own time
  // origin, so the phase numbers above are not comparable with the page's timeline on their own).
  BOOT.engineReadyWall = Date.now();
  self.__koBoot = BOOT;
  return true;
}

// Engine build-state invalidation. currentSpine/currentPages/builtKey describe what the ENGINE has
// built. Composed frames stay valid across a warm — a frame is a pure function of (book generation,
// spine, page, mode, render key, font stamp) — so the frame cache is NOT cleared here; only the
// tracking state is, and clearing on a load is explicit.
//
// §1 of the 1.1 audit: _ko_export_spine() internally calls g_driver->buildSection(spine, g_spec), so
// it changes the real C++ EngineDriver::section_ on every spine. Once preview renders may interleave
// with the warm, JS claiming "spine N is built" is a lie as soon as one export spine runs: the next
// uncached page of spine N would be rendered from whatever section_ the export last built. Section
// tracking therefore dies after EVERY export spine; the font cache only dies on a wholesale reset.
function invalidateSectionTracking() {
  currentSpine = -1;
  currentPages = 0;
  builtKey = null;
}
function invalidateEngine() {
  invalidateSectionTracking();
  appliedFont = null;          // the warm walked whole spines; re-send the face on the next spec
}

// Export the whole loaded book with the current spec, spine by spine (progress
// callback), returning the finished container bytes for download.
// opts.xtcz=true wraps the container in XTZ4 (LZ4) before copying out; the
// pre-wrap container size is reported as rawBytes (no JS-side unwrap needed).
// opts.cancelCheck() is polled between spines — returning true aborts early so
// a superseded background warm stops burning CPU (the half-built container is
// discarded; the next export begin() resets it).
async function exportWholeBook(opts, onProgress) {
  const xtcz = !!(opts && opts.xtcz);
  const cancelCheck = (opts && opts.cancelCheck) || null;
  tick('exportBegin');
  const spines = api._ko_export_begin();
  tock('exportBegin');
  if (spines < 0) throw new Error('export_begin failed');
  let total = 0;
  // Per-spine timing. Export is one engine doing every spine in order, so the only way to know
  // whether a spine pool is worth its complexity is to see the distribution: if 60 spines all cost
  // the same, N workers scale; if two spines are 80% of the work, they do not.
  const spineTimes = [];
  for (let s = 0; s < spines; s++) {
    tick('exportSpine');
    const tSpine = performance.now();
    const n = api._ko_export_spine(s);
    spineTimes.push({ spine: s, pages: n, ms: +(performance.now() - tSpine).toFixed(1) });
    tock('exportSpine');
    if (n < 0) {
      // abnormal exit: release the pages accumulated so far, then propagate
      api._ko_export_abort();
      invalidateSectionTracking();
      COUNTERS.aborts += 1;
      throw new Error('export spine ' + s + ' failed');
    }
    total += n;
    // §1: _ko_export_spine() just rebuilt the C++ section_ for THIS spine. Never let JS claim an
    // interactive spine is still built across this point.
    invalidateSectionTracking();
    if (onProgress) onProgress(s + 1, spines, total);
    // §4: yield after EVERY spine (measured: yielding every 4th let a page turn queue behind ~150 ms
    // of export work).
    COUNTERS.warmYields += 1;
    await yieldToLoop();
    if (cancelCheck && cancelCheck()) return cancelCurrentExport(total);
  }
  tick('exportFinish');
  const pages = api._ko_export_finish();
  tock('exportFinish');
  if (pages < 0) {
    api._ko_export_abort();
    invalidateSectionTracking();
    COUNTERS.aborts += 1;
    throw new Error('export_finish failed');
  }
  const rawBytes = api._ko_xtch_size();   // pre-wrap container size
  if (xtcz) {
    tick('xtczWrap');
    api._ko_xtcz_wrap();          // g_xtchOut → XTZ4 container in place
    tock('xtczWrap');
  }
  const ptr = api._ko_xtch_ptr();
  const size = api._ko_xtch_size();
  if (!ptr || size <= 0) {
    api._ko_export_abort();
    invalidateSectionTracking();
    COUNTERS.aborts += 1;
    throw new Error('export produced no bytes');
  }
  const out = new Uint8Array(api.HEAPU8.buffer.slice(ptr, ptr + size));
  api._ko_xtch_release();
  LAST_EXPORT.spines = spineTimes;
  LAST_EXPORT.preflight = preflightTimes;
  // Reported here as well as returned, because the *warm* path builds the container too — and the
  // warm is the common case in the app, so a report that only rides the explicit-export response is
  // invisible exactly when someone is looking at the conversion they just waited for.
  if (spineTimes.length && typeof console !== 'undefined' && console.log) {
    const ms = spineTimes.map((x) => x.ms).sort((a, b) => a - b);
    const sum = ms.reduce((a, b) => a + b, 0);
    const heaviest = Math.max(...ms);
    const speedup = (n) => sum / Math.max(sum / n, heaviest);
    console.log(`[export] ${spines} spines, ${pages} pages, ${sum.toFixed(0)} ms of spine work `
                + `(min ${ms[0].toFixed(1)} p50 ${ms[Math.floor(ms.length * 0.5)].toFixed(1)} `
                + `p90 ${ms[Math.floor(ms.length * 0.9)].toFixed(1)} max ${heaviest.toFixed(1)}) `
                + `ceiling ${speedup(4).toFixed(2)}x@4w ${speedup(8).toFixed(2)}x@8w`
                + (preflightTimes ? ` | preflight ${preflightTimes.ms} ms for ${preflightTimes.pages} pages` : ''));
  }
  return { file: out, pages, bytes: out.byteLength, spines, xtcz, rawBytes: rawBytes || 0 };
}

// Timing from the most recent export and preflight, for the `stats` command. Diagnostic only.
const LAST_EXPORT = { spines: [], preflight: null };
let preflightTimes = null;

// init runs once; every handler awaits it before touching the api
const initPromise = init();

// Apply the reader-face choice to the engine. Custom fonts need their bytes
// re-sent after every book load (ko_load_epub clears the in-memory FS).
// §1: which face the ENGINE currently has, and which custom-font generation it was built from.
// applyFont() used to run on every 'spec' — i.e. on every page turn — malloc'ing and re-parsing the
// whole .epdfont each time. Reset to null on load (the book load clears the engine's font state) and
// on clearFont, which is what makes the cache safe.
let appliedFont = null;
let appliedFontStamp = -1;

function applyFont(name) {
  const fontId = FONT_IDS[name];
  if (fontId === undefined) return false;
  if (name === 'custom') {
    if (!customFontBytes) return false;   // nothing uploaded yet → keep default
    if (appliedFont === 'custom' && appliedFontStamp === fontStamp) {
      COUNTERS.fontSkips += 1;
      return true;                        // already loaded, byte-for-byte the same font
    }
    const fp = api._malloc(customFontBytes.length);
    api.HEAPU8.set(customFontBytes, fp);
    const rc = api._ko_load_epdfont(fp, customFontBytes.length, customFontName);
    COUNTERS.epdfontLoads += 1;
    api._free(fp);
    if (rc === 0) { appliedFont = 'custom'; appliedFontStamp = fontStamp; }
    COUNTERS.fontApplies += 1;
    return rc === 0;
  }
  if (appliedFont === name && appliedFontStamp === fontStamp) {
    COUNTERS.fontSkips += 1;
    return true;                          // built-in already active
  }
  const ok = api._ko_set_font(fontId) === 0;
  if (ok) { appliedFont = name; appliedFontStamp = fontStamp; }
  COUNTERS.fontApplies += 1;
  return ok;
}

// §2/§3: one place that turns a spec object into engine state. The per-field setters are cheap
// (field writes in the engine) and run unconditionally so the spec is always authoritative; only the
// expensive parts are gated — the font (custom = malloc + copy + reparse) and the margins.
async function applySpec(raw) {
  const before = currentSpec;
  currentSpec = Object.assign(defaultSpec(), raw || {});
  const lkBefore = before ? layoutKey(before) : null;
  const rkBefore = before ? renderKey(before) : null;
  const lk = layoutKey(currentSpec);
  const rk = renderKey(currentSpec);
  COUNTERS.specApplies += 1;

  // The commit above is needed by every step below, but it must not SURVIVE a failure: a spec that
  // claims font:"custom" while the engine is still on KoPub makes every later applySpecIfChanged()
  // short-circuit on "no change" and render or export the wrong face silently. Measured with the
  // fail-closed test: the first call threw correctly, and the very next exportBook still produced a
  // KoPub file — because the failed spec had already been written down.
  try {

  api._ko_set_line_compression(currentSpec.lineCompression);
  api._ko_set_paragraph_indent(currentSpec.paragraphIndent);
  api._ko_set_character_wrap(currentSpec.characterWrap);
  api._ko_set_paragraph_alignment(currentSpec.paragraphAlignment);
  api._ko_set_extra_paragraph_spacing(currentSpec.extraParagraphSpacing);
  // Firmware gates hyphenation on word-wrap mode (CrossPointSettings::readerRenderSpec):
  // hyphenationEnabled = hyphenationEnabled && characterWrap == 0.
  api._ko_set_hyphenation((currentSpec.hyphenation && currentSpec.characterWrap === 0) ? 1 : 0);
  api._ko_set_embedded_style(currentSpec.embeddedStyle);
  api._ko_set_image_rendering(currentSpec.imageRendering);
  api._ko_set_text_aa(currentSpec.textAa);
  api._ko_set_image_dither(currentSpec.imageDither);
  api._ko_set_image_tone_depth(currentSpec.imageToneDepth);

  // Fetch the face before touching the engine with it: a lazily-loaded face (anything but the
  // default) may still be in flight, and `applyFont` would otherwise silently fail against a font id
  // that is not registered yet — rendering with the previous face and reporting success.
  if (currentSpec.font !== 'custom') {
    tick('ensureFace');
    await ensureFace(currentSpec.font);
    tock('ensureFace');
  }
  tick('applyFont');
  // Fail closed. applyFont() returns false when the requested face cannot be made active — a
  // custom font that was never uploaded to THIS engine, or a built-in whose blob could not be
  // registered. Continuing would render with whatever face was previously applied and still report
  // success, which is a wrong output that looks like a working one. With the preview and export
  // engines now separate, this is exactly how a custom-font export could have silently produced a
  // KoPub file.
  const fontOk = applyFont(currentSpec.font);
  tock('applyFont');
  if (!fontOk) {
    throw new Error('requested font "' + currentSpec.font + '" is not available in this engine');
  }

  if (lk !== lkBefore) {
    const mg = marginsFor(currentSpec);
    api._ko_set_margins(mg.top, mg.right, mg.bottom, mg.left);
    COUNTERS.layoutApplies += 1;
  }
  if (rk !== rkBefore) clearFrameCache();  // frames are keyed by render key: old ones are dead weight
  return { layout: lk, layoutChanged: lk !== lkBefore };

  } catch (e) {
    currentSpec = before;    // an unmet requirement must be re-attempted, not remembered as satisfied
    throw e;
  }
}

// Margins/viewport for the readout. The firmware's own arithmetic: viewable margins + screenMargin
// on all four sides, no UI reserve. Shared by the spec and render replies.
function viewportInfo(spec) {
  const mg = marginsFor(spec);
  return {
    margins: mg,
    viewport: { width: SCREEN_W - mg.left - mg.right, height: SCREEN_H - mg.top - mg.bottom },
  };
}

// The render path carries the spec, so an unchanged spec costs nothing at all (§2).
async function applySpecIfChanged(raw) {
  if (currentSpec && renderKey(currentSpec) === renderKey(Object.assign(defaultSpec(), raw || {}))) {
    COUNTERS.renderApplies += 1;
    return false;
  }
  await applySpec(raw);
  return true;
}


// Load-phase timings for the open path, so window.__koBookOpen can say WHERE the time went rather than
// only how much there was. Everything here is diagnostic and costs three performance.now() calls.
let loadTiming = {};

// What the engine did with images during the render it just performed. `decodes` is the number that
// matters: the page is rendered three times (BW, then LSB, then MSB), so unless the grey passes stop
// decoding, an image page decodes its image three times to produce one preview frame.
// The spine-label snapshot that used to live here is GONE. It contained a symptom: Driver::spineHref()
// returned `const std::string&` bound to `epub_->getSpineItem(i).href`, but getSpineItem() returns
// BookMetadataCache::SpineEntry BY VALUE, so the reference dangled and short hrefs were read out of a
// dead stack frame (the "䏆" / U+070F U+0006 garbage). spineHref() now returns std::string by value and
// ko_get_spine_href() copies into its own buffer, so labels are read on demand again, after the first
// frame, where an omnibus with thousands of spines should pay for them.

function readImagePerf() {
  if (!api || !api._ko_image_decodes) return null;
  try {
    return {
      decodes: api._ko_image_decodes(),
      images: api._ko_image_count(),
      readMs: +api._ko_image_perf(0).toFixed(2),
      headerMs: +api._ko_image_perf(1).toFixed(2),
      decodeMs: +api._ko_image_perf(2).toFixed(2),
      drawMs: +api._ko_image_perf(3).toFixed(2),
    };
  } catch (_) { return null; }
}

// Per-frame breakdown. `buildMs` is the section layout that has to finish before ANY page exists, which
// is exactly the number the progressive-layout work is meant to shrink.
function renderTiming(t0, buildMs, renderMs, composeMs, cached, imagePerf) {
  return {
    buildMs: +(buildMs || 0).toFixed(2),
    renderMs: +(renderMs || 0).toFixed(2),
    composeMs: +(composeMs || 0).toFixed(2),
    totalMs: +(performance.now() - t0).toFixed(2),
    pagesAvailable: currentPages,
    sectionComplete: api && api._ko_spine_build_complete ? api._ko_spine_build_complete() === 1 : true,
    cached: !!cached,
    image: imagePerf || undefined,
  };
}

function withCString(str, fn) {
  const bytes = new TextEncoder().encode(str == null ? '' : String(str));
  const ptr = api._malloc(bytes.length + 1);
  try {
    api.HEAPU8.set(bytes, ptr);
    api.HEAPU8[ptr + bytes.length] = 0;
    return fn(ptr);
  } finally {
    api._free(ptr);
  }
}

// ---- progressive section build -------------------------------------------------
// A spine is laid out one page at a time until the first page exists, then extended in chunks while
// the reader looks at it. Measured on a 326-page single spine: 48.8 ms of a 68.2 ms first page was
// section layout, so this is the difference between "wait for the chapter" and "wait for one page".
const FIRST_PAGES = 1;      // enough for the requested page to exist
const BUILD_CHUNK = 4;      // pages per continuation tick
let sectionGen = 0;         // bumped by anything that replaces the live section
let sectionEstimates = {};

// Anything that mutates the engine's live section must bump this, or a continuation would keep laying
// out a section nobody is looking at (and could interleave with an export's own buildSection).
function invalidateSection() { sectionGen += 1; }


async function continueSection(spine, gen, chunk) {
  while (gen === sectionGen && currentSpine === spine && !foregroundExportRunning && !warmRunning) {
    if (api._ko_spine_build_complete() === 1) break;
    const t0 = performance.now();
    const n = api._ko_build_spine_more(chunk);
    if (n < 0) break;
    currentPages = api._ko_spine_pages_available();
    const est = api._ko_spine_pages_estimated();
    const done = api._ko_spine_build_complete() === 1;
    sectionEstimates[spine] = { pages: currentPages, estimated: est, complete: done };
    // Progress carries no id: the page updates its "x / y" total without a round trip.
    self.postMessage({ sectionProgress: true, spine, pages: currentPages, estimated: est,
                       complete: done, ms: +(performance.now() - t0).toFixed(2) });
    if (done) break;
    await yieldToLoop();          // let render / navigation / settings messages run between chunks
  }
  if (gen === sectionGen && currentSpine === spine && api._ko_spine_build_complete() === 1) {
    sectionEstimates[spine] = { pages: currentPages, estimated: currentPages, complete: true };
    self.postMessage({ sectionProgress: true, spine, pages: currentPages, estimated: currentPages,
                       complete: true, ms: 0 });
  }
}

// `early` = {promise, startedAt} for a read the caller started BEFORE awaiting initPromise. The read needs
// no engine, so on a cold page load the module's fetch/compile and the file read overlap instead of
// running back to back. Everything below is otherwise unchanged, including the ownership contract.
async function loadEngineBook(data, timing, early) {
  const t0 = performance.now();
  if (data.epub) {
    const bytes = new Uint8Array(data.epub);
    const tCopy = performance.now();
    const ptr = api._malloc(bytes.length);
    api.HEAPU8.set(bytes, ptr);
    timing.wasmCopyMs = performance.now() - tCopy;
    timing.path = 'copy(ArrayBuffer)';
    const t = performance.now();
    const n = api._ko_load_epub(ptr, bytes.length, '/book.epub');
    timing.engineLoadMs = performance.now() - t;
    api._free(ptr);                       // ko_load_epub copies; this buffer stays ours
    timing.totalLoadMs = performance.now() - t0;
    return n;
  }
  const blob = data.blob;

  if (data.streamEpub && blob && blob.stream && api._ko_epub_alloc && api._ko_load_epub_owned) {
    const size = blob.size;
    const ptr = api._ko_epub_alloc(size);
    if (ptr) {
      let off = 0, overflow = false;
      const tStream = performance.now();
      const reader = blob.stream().getReader();
      for (;;) {
        const { value, done } = await reader.read();
        if (done) break;
        if (off + value.byteLength > size) { overflow = true; break; }
        api.HEAPU8.set(value, ptr + off);
        off += value.byteLength;
      }
      timing.streamMs = performance.now() - tStream;
      if (!overflow && off === size) {
        timing.path = 'stream+own';
        const t = performance.now();
        const n = api._ko_load_epub_owned(ptr, size, '/book.epub');
        timing.engineLoadMs = performance.now() - t;
        timing.totalLoadMs = performance.now() - t0;
        return n;   // ownership went with the call, in both outcomes
      }
      api._free(ptr);                     // streaming failed: the buffer is still ours
      timing.streamFallback = true;
    }
  }

  // The read and the heap allocation are independent, so start the read first and allocate while it is
  // in flight. `wasmAllocMs` and `wasmMemcpyMs` are separate because they have different fixes: growth
  // can overlap I/O, a memcpy cannot.
  let readPromise;
  let readStartedAt;
  if (early && early.promise) {
    readPromise = early.promise;
    readStartedAt = early.startedAt;           // may be before initPromise resolved
  } else {
    readStartedAt = performance.now();
    readPromise = blob.arrayBuffer();
  }
  const tAlloc = performance.now();
  const ptr = api._ko_epub_alloc ? api._ko_epub_alloc(blob.size) : api._malloc(blob.size);
  timing.wasmAllocMs = performance.now() - tAlloc;
  if (!ptr) {
    await readPromise.catch(() => {});
    throw new Error('EPUB allocation failed');
  }
  const tWait = performance.now();
  const buf = await readPromise;
  const waitedFor = performance.now() - tWait;
  const readDone = performance.now();
  const bytes = new Uint8Array(buf);
  const tCopy = performance.now();
  api.HEAPU8.set(bytes, ptr);
  timing.wasmMemcpyMs = performance.now() - tCopy;
  // Read wall time from when it STARTED (possibly before init) plus the part still outstanding once the
  // engine was ready; the difference is what the overlap actually bought.
  timing.blobReadMs = +(readDone - readStartedAt).toFixed(2);
  timing.blobWaitAfterInitMs = +waitedFor.toFixed(2);
  timing.blobBootOverlapMs = +Math.max(0, timing.blobReadMs - waitedFor).toFixed(2);
  timing.wasmCopyMs = timing.wasmMemcpyMs;
  if (api._ko_load_epub_owned) {
    // Adopt: storage takes this buffer, so the book is not copied again in C++.
    //
    // OWNERSHIP IS CONSUMED BY THE CALL, SUCCESS OR FAILURE. There is deliberately no fallback to
    // ko_load_epub after this: the driver mounts the blob before it parses, so a failed parse has
    // already dropped it — which frees this pointer. Re-entering the copying path would read from
    // transferred memory, and the api._free() that path ends with would be a double free. A parse
    // failure is also not something a copy would fix: the same bytes would fail identically.
    timing.path = 'read+adopt';
    const t = performance.now();
    const n = api._ko_load_epub_owned(ptr, bytes.length, '/book.epub');
    timing.engineLoadMs = performance.now() - t;
    timing.totalLoadMs = performance.now() - t0;
    return n;
  }
  // The copying path exists only for a module whose API predates ko_load_epub_owned: here the buffer
  // was never handed over, so it is still ours to free.
  timing.path = 'copy(Blob)';
  const t = performance.now();
  const n = api._ko_load_epub(ptr, bytes.length, '/book.epub');
  timing.engineLoadMs = performance.now() - t;
  api._free(ptr);
  timing.totalLoadMs = performance.now() - t0;
  return n;
}

self.onmessage = async (ev) => {
  const { id, cmd } = ev.data;
  let earlyRead = null;
  const t0Open = performance.now();
  try {
    // Start the file read BEFORE waiting for the engine. Reading a File/Blob needs no WASM, and on a cold
    // page load this is the one place where the two unavoidable startup costs can overlap. The streaming
    // path manages its own read and the ArrayBuffer path has nothing to read, so both are excluded.
    //
    // `noEarlyRead` is the CONTROL for measuring it: the same build, the same book, one variable — the
    // read either starts before `await initPromise` or after it, exactly as it did before this change.
    if ((cmd === 'load' || cmd === 'openPreview') && ev.data.blob && !ev.data.streamEpub
        && !ev.data.noEarlyRead && typeof ev.data.blob.arrayBuffer === 'function') {
      const promise = ev.data.blob.arrayBuffer();
      promise.catch(() => {});            // init may fail first; do not surface an unhandled rejection
      earlyRead = { promise, startedAt: performance.now() };
    }
    const tInit0 = performance.now();
    await initPromise;   // engine ready before any command
    const initWaitMs = performance.now() - tInit0;
    switch (cmd) {      case 'ping': {
        const vp = api._ko_version();
        const ver = api.UTF8ToString ? api.UTF8ToString(vp) : String(vp);
        post(id, true, { version: ver });
        break;
      }

      // Cold-boot phases, plus the browser's own accounting of the engine fetch. The resource
      // entry answers the question the phase numbers cannot: whether the time went into the
      // network or into compilation/instantiation. `encodedBodySize` is what crossed the wire,
      // `decodedBodySize` what had to be compiled.
      case 'bootstats': {
        const boot = self.__koBoot || {};
        let resource = null;
        if (typeof performance !== 'undefined' && performance.getEntriesByType) {
          // Match the WASM specifically: 'ko_xtch_wasm.' also matches the 19 KB glue, which is how
          // the first version of this reported a 19 KB engine fetch as the engine's own transfer.
          const e = performance.getEntriesByType('resource')
            .find((x) => x.name && /ko_xtch_wasm\.[a-f0-9]+\.wasm|ko_xtch_wasm\.wasm/.test(x.name));
          if (e) {
            resource = {
              encodedBodySize: e.encodedBodySize,
              decodedBodySize: e.decodedBodySize,
              transferSize: e.transferSize,
              downloadMs: +(e.responseEnd - e.responseStart).toFixed(1),
            };
          }
        }
        post(id, true, { phases: boot.phases || null, workerStart: boot.workerStart || 0,
                         engineReadyWall: boot.engineReadyWall || 0, resource,
                         embedded: embeddedFaces(), lazyFaces: boot.lazyFaces || [],
                         facesRegistered: boot.facesRegistered || [], faceError: boot.faceError || null });
        break;
      }

      case 'load': {
        if (foregroundExportRunning) { post(id, false, { error: 'book locked during export' }); break; }
        if (!api) await init();
        // §2: stop the warm and WAIT for it before the engine's EPUB is replaced. Bumping the token
        // alone only asks it to abort at its next spine yield, and the suspended warm handler would
        // then resume its spine loop against the NEW book.
        await stopWarmBeforeMutation();
        // EITHER an ArrayBuffer or a Blob. A Blob matters now that two engines exist: an ArrayBuffer
        // handed to one worker is DETACHED by the transfer, so the second engine could never read it,
        // and keeping a second copy in the page would double the book's memory for a 200 MB book.
        // Each worker reads the same Blob instead.
        dropWarmResult();     // §3: warm bytes belong to the previous book
        invalidateSection();
        loadTiming = { initWaitMs: +initWaitMs.toFixed(2) };
        spineCount = await loadEngineBook(ev.data, loadTiming, earlyRead);
        loadTiming.bookBytes = ev.data.epub ? ev.data.epub.byteLength : (ev.data.blob ? ev.data.blob.size : 0);
        loadTiming.heapAfterLoadBytes = api.HEAPU8.buffer.byteLength;
        if (spineCount < 0) {
          post(id, false, { error: 'Epub::load failed' });
          return;
        }
        // title
        const tbuf = api._malloc(512);
        api._ko_get_title(tbuf, 512);
        const title = api.UTF8ToString(tbuf);
        api._free(tbuf);
        currentSpine = -1;
        currentPages = 0;
        bookGen += 1;                // §5: new book, new frame namespace
        clearFrameCache();
        appliedFont = null;          // §1: a load resets the engine's font state, so force a re-apply
        // a new book cleared the in-memory FS: re-apply the custom font if one
        // is loaded, so the reader face survives chapter navigation
        if (customFontBytes && currentSpec && currentSpec.font === 'custom') {
          // a new book cleared the in-memory FS, so the custom font has to go back in; if that fails
          // the engine would render this book with the default face while the page believes otherwise
          if (!applyFont('custom')) {
            const ep = api._ko_error();
            post(id, false, { error: 'epdfont re-apply after book load failed: ' +
                                     (api.UTF8ToString(ep) || 'failed') });
            return;
          }
        }
        // totalLoadMs is set by loadEngineBook (it owns the whole sequence, including the font re-apply
        // deadline above it); nothing to add here.
        // Spine labels are NOT sent here: one label per spine in front of the first page buys nothing,
        // and an omnibus has thousands. The page asks for them in batches once the first frame is up.
        // Where the reference reader would open: its own text reference, not always spine 0. The page
        // starts there; the container still holds every spine.
        const startSpine = api._ko_text_reference_spine ? api._ko_text_reference_spine() : 0;
        post(id, true, { spineCount, title, startSpine, timing: loadTiming });
        break;
      }

      case 'spec': {
        if (foregroundExportRunning) { post(id, false, { error: 'settings locked during export' }); break; }
        // §3 of the 1.4 audit: the worker owns this invariant, not the caller. window.__call is
        // exposed for debugging, so a raw spec during a warm must not change g_spec between spines.
        await stopWarmBeforeMutation();
        tick('spec');
        // margins: viewable area + screenMargin on all four sides (no UI reserve)
        await applySpec(ev.data.spec);
        const vp = viewportInfo(currentSpec);
        tock('spec');
        post(id, true, {
          specKey: layoutKey(currentSpec),          // layout key: the only thing that repaginates
          renderKey: renderKey(currentSpec),
          layoutChanged: true,
          margins: vp.margins,
          viewport: vp.viewport,
        });
        break;
      }

      case 'build': {
        tick('build');
        const n = api._ko_build_spine(ev.data.spine);
        tock('build');
        if (n < 0) {
          const ep = api._ko_error();
          const msg = api.UTF8ToString(ep) || 'build failed';
          post(id, false, { error: 'build failed: ' + msg });
          return;
        }
        currentSpine = ev.data.spine;
        currentPages = n;
        post(id, true, { pages: n });
        break;
      }

      // P3: open + first page in ONE round trip. First open otherwise costs
      //   page->worker load, worker->page metadata, page UI work, page->worker render, worker->page frame
      // and nothing about the first page needs that middle hop. `load` is kept for export/pool workers,
      // which want metadata without a preview frame.
      case 'openPreview': {
        if (foregroundExportRunning) { post(id, false, { error: 'book locked during export' }); break; }
        if (!api) await init();
        await stopWarmBeforeMutation();
        dropWarmResult();
        invalidateSection();
        loadTiming = { initWaitMs: +initWaitMs.toFixed(2) };
        spineCount = await loadEngineBook(ev.data, loadTiming, earlyRead);
        loadTiming.bookBytes = ev.data.epub ? ev.data.epub.byteLength
                                            : (ev.data.blob ? ev.data.blob.size : 0);
        loadTiming.heapAfterLoadBytes = api.HEAPU8.buffer.byteLength;
        if (spineCount < 0) {
          post(id, false, { error: 'Epub::load failed', timing: loadTiming });
          return;
        }
        const titleBuf = api._malloc(512);
        api._ko_get_title(titleBuf, 512);
        const openTitle = api.UTF8ToString(titleBuf);
        api._free(titleBuf);
        bookGen += 1;
        currentSpine = -1;
        currentPages = 0;
        if (ev.data.spec) await applySpec(ev.data.spec);
        const startSpine = api._ko_text_reference_spine ? api._ko_text_reference_spine() : 0;
        const tBuild0 = performance.now();
        const pages = api._ko_start_spine(startSpine, FIRST_PAGES);
        if (pages < 0) {
          post(id, false, { error: 'build failed: ' + (api.UTF8ToString(api._ko_error()) || 'unknown'),
                            timing: loadTiming });
          return;
        }
        currentSpine = startSpine;
        currentPages = pages;
        builtKey = layoutKey(currentSpec || {});
        builtFontStamp = fontStamp;
        const buildMs = performance.now() - tBuild0;
        const wantMono = ev.data.mode === 0;
        const tRender0 = performance.now();
        const rc = renderPageEngine(0, wantMono);
        if (rc !== 0) {
          post(id, false, { error: 'first page render failed', timing: loadTiming });
          return;
        }
        const renderMs = performance.now() - tRender0;
        const tCompose0 = performance.now();
        const frame = wantMono ? composeMono() : composePage();
        const composeMs = performance.now() - tCompose0;
        const gen = sectionGen;
        const tx = frame.data.buffer;
        post(id, true, {
          title: openTitle,
          spineCount,
          startSpine,
          page: 0,
          pages,
          total: Math.max(pages, api._ko_spine_pages_estimated ? api._ko_spine_pages_estimated() : pages),
          image: tx,
          mono: wantMono,
          cached: false,
          timing: Object.assign({}, loadTiming,
                                renderTiming(tRender0, buildMs, renderMs, composeMs, false, readImagePerf()),
                                { totalOpenWorkerMs: +(performance.now() - t0Open).toFixed(2) }),
        }, [tx]);
        // The rest of the spine keeps building behind the drawn frame.
        continueSection(startSpine, gen, BUILD_CHUNK);
        break;
      }

      case 'render': {
        // §2/§8: the spec travels with the render, so an ordinary page turn is one request and a
        // settings change is one request too. When it has not changed, this does nothing at all.
        let vpInfo = null;
        if (ev.data.spec) {
          const incomingSpec = Object.assign(defaultSpec(), ev.data.spec);
          const changesSpec = renderKey(incomingSpec) !== renderKey(currentSpec || {});
          // §1: a render carrying a CHANGED spec mutates engine state, so it is refused during a
          // foreground export. Navigation with an unchanged (or absent) spec stays fully allowed.
          if (changesSpec && foregroundExportRunning) {
            post(id, false, { error: 'settings locked during export' });
            break;
          }
          // §3: and it must not change g_spec underneath a running warm either
          if (changesSpec) await stopWarmBeforeMutation();
          if (await applySpecIfChanged(ev.data.spec)) vpInfo = viewportInfo(currentSpec);
        }
        const tRender0 = performance.now();
        const key = layoutKey(currentSpec || {});
        const wantMono = ev.data.mode === 0;   // 1-bit XTC preview (BW plane only)
        // rebuild if spine, LAYOUT, OR loaded font changed since the last build
        // (a custom-font swap changes glyphs/metrics but not the worker spec;
        //  pixel-only options like AA/dither/tone depth must not repaginate — §3)
        let continuation = null;
        if (ev.data.spine !== currentSpine || key !== builtKey ||
            fontStamp !== builtFontStamp) {
          COUNTERS.builds += 1;
          tick('rebuild');
          let n;
          if (ev.data.progressive === false) {
            n = api._ko_build_spine(ev.data.spine);       // one-shot (the gate's reference path)
          } else {
            invalidateSection();
            const gen = sectionGen;
            n = api._ko_start_spine(ev.data.spine, FIRST_PAGES);
            if (n >= 0) continuation = { spine: ev.data.spine, gen };
          }
          tock('rebuild');
          if (n < 0) {
            const ep = api._ko_error();
            const msg = api.UTF8ToString(ep) || 'build failed';
            post(id, false, { error: 'build failed: ' + msg });
            return;
          }
          currentSpine = ev.data.spine;
          currentPages = n;
          builtKey = key;
          builtFontStamp = fontStamp;
          sectionEstimates[ev.data.spine] = {
            pages: n,
            estimated: api._ko_spine_pages_estimated(),
            complete: api._ko_spine_build_complete() === 1,
          };
        }
        const buildMs = performance.now() - tRender0;
        let page = ev.data.page;
        if (page < 0) page = 0;
        if (page >= currentPages) page = currentPages - 1;
        // Repeat navigation: the composed frame is a pure function of these five inputs, and
        // the cached copy is already out of wasm memory.
        const rk = renderKey(currentSpec || {});
        const frameKey = bookGen + ':' + currentSpine + ':' + page + ':' + (wantMono ? 1 : 0) + ':' + rk + ':' + builtFontStamp;
        const cachedFrame = frameCacheGet(frameKey);
        if (cachedFrame) {
          COUNTERS.cacheHits += 1;
          const reply = new Uint8ClampedArray(cachedFrame.data.length);
          reply.set(cachedFrame.data);
          post(id, true, { page, pages: currentPages, image: reply.buffer, mono: wantMono, cached: true,
                           timing: renderTiming(tRender0, 0, 0, 0, true, null),
                           viewport: vpInfo ? vpInfo.viewport : null,
                           margins: vpInfo ? vpInfo.margins : null },
               [reply.buffer]);
          // §5: a hit must also extend the chain, or sequential reading only covers every other turn.
          schedulePrefetch(currentSpine, page, currentPages, wantMono, rk, builtFontStamp, bookGen);
          break;
        }

        tick('renderPage');
        COUNTERS.renders += 1;
        const tRenderStart = performance.now();
        const rc = renderPageEngine(page, wantMono);
        tock('renderPage');
        const renderMs = performance.now() - tRenderStart;
        const imgPerf = readImagePerf();
        if (rc !== 0) { post(id, false, { error: 'render failed' }); return; }
        // No plane copies: the compose runs inside the engine and reads the engine's own
        // planes, so copying 3 x 48 KB out of wasm here was pure waste.
        tick('compose');
        // compose through the SAME quantization the encoder uses for the chosen
        // mode: 1-bit → BW plane only (no AA greys), 2-bit → full 4-level
        const tCompose0 = performance.now();
        const img = wantMono ? composeMono() : composePage();
        const composeMs = performance.now() - tCompose0;
        tock('compose');
        frameCachePut(frameKey, img.data);      // copied: this buffer is transferred below
        const tx = img.data.buffer;
        COUNTERS.framesPosted += 1;
        // §2: user-visible work is finished — send it NOW. The prefetch is speculative and must never
        // delay the requested frame (it used to run between compose() and post()).
        const est = sectionEstimates[currentSpine] || { pages: currentPages, estimated: currentPages, complete: true };
        post(id, true, { page, pages: currentPages, image: tx, mono: wantMono,
                         // `pages` is what EXISTS (navigation clamps to it); `total` is what to display —
                         // a giant spine still building knows its estimate, not its final count.
                         total: est.complete ? currentPages : Math.max(est.estimated || 0, currentPages),
                         sectionComplete: !!est.complete,
                         timing: renderTiming(tRender0, buildMs, renderMs, composeMs, false, imgPerf),
                         viewport: vpInfo ? vpInfo.viewport : null,
                         margins: vpInfo ? vpInfo.margins : null }, [tx]);
        if (continuation) continueSection(continuation.spine, continuation.gen, BUILD_CHUNK);
        schedulePrefetch(currentSpine, page, currentPages, wantMono, rk, builtFontStamp, bookGen);
        break;
      }

      case 'cover': {
        // generate cover BMP in the engine and return raw BMP bytes
        const rc = api._ko_generate_cover(ev.data.kind || 0);
        if (rc !== 0) {
          const ep = api._ko_error();
          post(id, false, { error: 'cover gen: ' + (api.UTF8ToString(ep) || 'failed') });
          return;
        }
        const ptr = api._ko_cover_ptr();
        const size = api._ko_cover_size();
        const bytes = new Uint8Array(api.HEAPU8.buffer.slice(ptr, ptr + size));
        const tx = bytes.buffer;
        post(id, true, { cover: tx }, [tx]);
        break;
      }

      case 'convertFont': {
        if (foregroundExportRunning) { post(id, false, { error: 'font locked during export' }); break; }
        // TTF/OTF -> .epdfont, in this worker. This is the ONLY conversion path on the
        // hosted build (no backend there), and app.js prefers it locally too: the font
        // bytes never leave the tab and a full Hangul font lands in ~150-400 ms.
        // Parity with tools/ttf_to_epdfont_fast.py is byte-for-byte on every case
        // measured (scripts/verify/epdfont_parity.js).
        tick('convertFont');
        const conv = await getFontConverter();
        const res = conv.convert({
          fontBytes: new Uint8Array(ev.data.font),
          name: ev.data.name || 'custom',
          size: ev.data.size || 14,
          twoBit: ev.data.twoBit !== false,
          weight: ev.data.weight || 500,
          noHangul: !!ev.data.noHangul,
          extraIntervals: ev.data.extraIntervals || [],
          spacePx: ev.data.spacePx,
        });
        const buf = res.bytes.buffer;
        tock('convertFont');
        post(id, true, {
          epdfont: buf,
          meta: {
            glyphs: res.glyphCount, intervals: res.intervalCount, bitmapBytes: res.bitmapBytes,
            advanceY: res.advanceY, ascender: res.ascender, descender: res.descender,
            weightMode: res.weightMode, effectiveWeight: res.effectiveWeight,
            nativeWeight: res.nativeWeight, emboldenPx64: res.emboldenPx64,
            ftVersion: ftVersionString,
          },
        }, [buf]);
        break;
      }

      case 'loadFont': {
        if (foregroundExportRunning) { post(id, false, { error: 'font locked during export' }); break; }
        await stopWarmBeforeMutation();
        // ev.data.epdfont: ArrayBuffer, ev.data.name: string
        tick('loadFont');
        customFontBytes = new Uint8Array(ev.data.epdfont);
        customFontName = (ev.data.name || 'custom').replace(/[^\w-]/g, '') || 'custom';
        fontStamp++;
        clearFrameCache();    // §6: frames keyed by the old stamp can never hit again
        tick('applyFont');
        const ok = applyFont('custom');
        tock('applyFont');
        tock('loadFont');
        if (!ok) {
          const ep = api._ko_error();
          post(id, false, { error: 'epdfont load: ' + (api.UTF8ToString(ep) || 'failed') });
          return;
        }
        post(id, true, { font: 'custom', fontStamp });
        break;
      }

      case 'clearFont': {
        if (foregroundExportRunning) { post(id, false, { error: 'font locked during export' }); break; }
        await stopWarmBeforeMutation();
        customFontBytes = null;
        fontStamp++;
        clearFrameCache();    // §6: frames keyed by the old stamp can never hit again
        appliedFont = null;          // §1: face selection must be re-sent
        api._ko_clear_custom_font();
        currentSpec = Object.assign(currentSpec || defaultSpec(), { font: defaultSpec().font });
        post(id, true, { font: defaultSpec().font, fontStamp });
        break;
      }

      case 'warm': {
        // Background whole-book conversion (settings settled → pre-render the
        // book so the file is ready when the user hits export). Mirrors the
        // exportBook pipeline but WITHOUT transferring megabytes back to the
        // app: the finished container stays in the worker, and the app pulls
        // it only on download via 'fetchWarm'. warmToken lets a newer warm
        // supersede an in-flight one.
        const myTok = ev.data.token || 0;
        if (myTok < warmToken) { post(id, true, { warm: 'superseded' }); break; }
        warmToken = Math.max(warmToken, myTok);   // adopt: newer warms supersede
        if (warmRunning) { post(id, true, { warm: 'busy' }); break; }
        beginWarm();
        // The warm pass drives the engine through every spine; the JS tracker
        // (currentSpine) can't follow, so any render that interleaves between
        // the warm's spine yields must force a rebuild of its own spine.
        invalidateEngine();
        dropWarmResult();     // §3: never hold this warm plus a previous one
        try {
          tick('warm');
          // §3 of the 1.3 audit: the warm carries the spec it is producing, so it does not depend on
          // a preview render having already applied the same settings.
          if (ev.data.spec) await applySpecIfChanged(ev.data.spec);
          // §1 of the 1.4 audit: this local used to be named warmMode, shadowing the module-level
          // metadata variable — the assignment further down then threw "Assignment to constant
          // variable" AFTER the whole book was rendered, so the warm never reported ready.
          const selectedWarmMode = ev.data.mode === 0 ? 0 : 1;
          api._ko_export_set_mode(selectedWarmMode);
          // the tone depth must follow the MODE (a 1-bit page packs 2 tones); the warm previously
          // inherited whatever the spec said, so a 1-bit warm could pack 4-level pages into one plane
          const warmDepth = selectedWarmMode === 0 ? 2 : 4;
          api._ko_set_image_tone_depth(warmDepth);
          if (currentSpec) currentSpec.imageToneDepth = warmDepth;
          // No size preflight and no cap. The preflight paginated every spine to decide whether to
          // paginate every spine, so a book that passed it was laid out TWICE, and a book that failed
          // it was laid out once for nothing and then again at export time. Both were artefacts of
          // sharing this engine with the reader; with a dedicated export engine there is no
          // interactive work here to starve, so the honest thing is to convert the book the user
          // asked for.
          //
          // Cancellation is still cheap: a superseding warm bumps the token and the loop checks it at
          // every spine, and the app terminates this worker outright when the request itself changes.
          const res = await exportWholeBook({
            mode: selectedWarmMode,
            xtcz: !!ev.data.xtcz,
            cancelCheck: () => myTok < warmToken,   // a newer warm superseded us
          });
          if (myTok < warmToken) { post(id, true, { warm: 'superseded' }); break; }
          if (res.cancelled) { post(id, true, { warm: 'cancelled' }); break; }
          warmBytes = res.file;
          warmPages = res.pages;
          warmRaw = res.rawBytes || 0;
          warmMode = selectedWarmMode;      // module-level metadata
          warmXtcz = !!ev.data.xtcz;
          tock('warm');
          invalidateEngine();
          post(id, true, { warm: 'ready', pages: res.pages,
                           spineTimes: LAST_EXPORT.spines, preflight: LAST_EXPORT.preflight });
        } finally {
          invalidateSectionTracking();   // §1: also on a cancelled or superseded warm
          endWarm();
        }
        break;
      }

      case 'warmCancel': {
        // settings changed mid-warm → tell the in-flight warm to abort at the
        // next spine yield (it polls myTok < warmToken). No new warm starts;
        // the app will fire one again once the user settles.
        warmToken++;
        dropWarmResult();     // §3: a superseded/cancelled warm's megabytes must not linger
        post(id, true, { warmCancel: true });
        break;
      }

      case 'fetchWarm': {
        if (!warmBytes) { post(id, false, { error: 'no warm bytes' }); break; }
        const tx = takeTransferBuffer(warmBytes)   // §2: no full-file copy;
        const meta = { pages: warmPages, mode: warmMode, xtcz: warmXtcz, rawBytes: warmRaw };
        warmBytes = null;   // hand over once
        post(id, true, Object.assign({ file: tx }, meta), [tx]);
        break;
      }

      case 'warmState': {
        post(id, true, { has: !!warmBytes, pages: warmPages, mode: warmMode, xtcz: warmXtcz });
        break;
      }

// Call fn(ptr) with a NUL-terminated UTF-8 copy of `str` in wasm memory. Written out explicitly
// instead of relying on the JS glue to marshal a string for a char* argument: it is not obvious from
// the call site whether that conversion happens, and a silently-null path is exactly the kind of thing
// that would produce a container with missing chapter names and no error.
      case 'spineHrefs': {
        // On demand again: safe because ko_get_spine_href() copies the href into its own buffer instead of
        // pointing into a by-value temporary (see the note where the snapshot used to be).
        const start = Math.max(0, ev.data.start | 0);
        const count = Math.max(1, ev.data.count | 0);
        const end = Math.min(spineCount, start + count);
        const hrefs = [];
        for (let s = start; s < end; s++) {
          hrefs.push(api.UTF8ToString(api._ko_get_spine_href(s)));
        }
        post(id, true, { start, hrefs });
        break;
      }

      case 'timing': {
        post(id, true, { load: loadTiming, counters: COUNTERS });
        break;
      }

      case 'encodeSpine': {
        // ONE spine, laid out + rendered + ENCODED on this engine, returned as a single transferable
        // buffer. This is the unit of parallel work: rendering is ~85% of export time and it is
        // per-spine work, while the container is not. Page encoding is unchanged — the same writer
        // the serial path uses, on a spine-local basis.
        if (foregroundExportRunning) { post(id, false, { error: 'export already running' }); break; }
        foregroundExportRunning = true;
        try {
          await stopWarmBeforeMutation();
          if (ev.data.spec) await applySpecIfChanged(ev.data.spec);
          const m = ev.data.mode === 0 ? 0 : 1;
          api._ko_export_set_mode(m);
          api._ko_set_image_tone_depth(m === 0 ? 2 : 4);
          if (currentSpec) currentSpec.imageToneDepth = m === 0 ? 2 : 4;
          const spine = ev.data.spine | 0;
          invalidateSection();
          const n = api._ko_encode_spine(spine);
          if (n < 0) { post(id, false, { error: 'encode spine failed: ' + spine }); break; }
          const ptr = api._ko_spine_data_ptr();
          const size = api._ko_spine_data_size();
          const bytes = api.HEAPU8.slice(ptr, ptr + size);
          // Only the per-page LENGTHS cross; offsets are their prefix sum, derivable exactly.
          const lptr = api._ko_spine_page_lengths();
          const lengths = Array.from(new Uint32Array(api.HEAPU8.buffer, lptr, n));
          const tocN = api._ko_spine_toc_count();
          const toc = [];
          for (let i = 0; i < tocN; i++) {
            toc.push({ tocIndex: api._ko_spine_toc_index(i),
                       localPage: api._ko_spine_toc_local_page(i),
                       title: api.UTF8ToString(api._ko_spine_toc_title(i)) });
          }
          post(id, true, {
            spine, pageCount: n, bytes: bytes.buffer, lengths, toc,
            fallbackName: api.UTF8ToString(api._ko_spine_fallback_name()),
          }, [bytes.buffer]);
        } finally {
          foregroundExportRunning = false;
        }
        break;
      }

      case 'planPrefix': {
        // Prefix-only assembly: the records never enter an engine. The container's fixed region is a
        // function of the page SIZES and the chapters, so this returns ~10 KB of header/metadata/
        // chapter-table/index and the caller composes [prefix][records…] in the browser. Uncompressed
        // XTC/XTCH only — XTCZ needs the byte stream, so it uses assembleSpines.
        const mode = ev.data.mode === 0 ? 0 : 1;
        if (api._ko_plan_begin(mode) < 0) { post(id, false, { error: 'plan begin failed' }); break; }
        let base = 0;
        let recordBytes = 0;
        let bad = null;
        for (const sp of (ev.data.spines || [])) {
          const pages = sp.pageCount | 0;
          if (pages <= 0) continue;                       // matches the serial path's `if (added > 0)`
          const lengths = Uint32Array.from(sp.lengths || []);
          if (lengths.length !== pages) { bad = 'spine ' + sp.spine + ': ' + lengths.length + ' lengths for ' + pages + ' pages'; break; }
          const lptr = api._malloc(pages * 4);
          try {
            new Uint32Array(api.HEAPU8.buffer, lptr, pages).set(lengths);
            if (api._ko_plan_add_spine(lptr, pages) < 0) { bad = 'plan add spine failed'; break; }
          } finally {
            api._free(lptr);
          }
          for (const t of (sp.toc || [])) {
            withCString(t.title, (tp) => api._ko_plan_add_toc(base, tp, t.localPage | 0));
          }
          withCString(sp.fallbackName, (fp) => api._ko_plan_add_fallback(base, fp, pages));
          for (let i = 0; i < pages; i++) recordBytes += lengths[i];
          base += pages;
        }
        if (bad) { post(id, false, { error: bad }); break; }
        const total = api._ko_plan_finish();
        if (total < 0) { post(id, false, { error: 'plan finish failed' }); break; }
        const pptr = api._ko_plan_prefix_ptr();
        const psize = api._ko_plan_prefix_size();
        const prefix = api.HEAPU8.slice(pptr, pptr + psize);
        post(id, true, { pages: total, spinePages: base, prefix: prefix.buffer,
                         prefixBytes: psize, recordBytes, rawBytes: psize + recordBytes },
             [prefix.buffer]);
        break;
      }

      case 'assembleSpines': {
        // ONE assembler writes the container. The records arrive already encoded; this only appends
        // them in the order the caller sent (spine order) and builds the chapter table with the same
        // shared builder the serial path uses. Completion order must never reach this code, so the
        // caller is responsible for sending spines in index order.
        const mode = ev.data.mode === 0 ? 0 : 1;
        if (api._ko_assemble_begin(mode) < 0) { post(id, false, { error: 'assemble begin failed' }); break; }
        let base = 0;
        let raw = 0;
        let bad = null;
        for (const sp of (ev.data.spines || [])) {
          const pages = sp.pageCount | 0;
          if (pages <= 0) continue;                     // matches the serial path's `if (added > 0)`
          const lengths = sp.lengths;
          const bytes = new Uint8Array(sp.bytes);
          const offs = new Uint32Array(pages);
          let acc = 0;
          for (let i = 0; i < pages; i++) { offs[i] = acc; acc += lengths[i]; }
          if (acc !== bytes.length) { bad = 'spine ' + sp.spine + ': lengths sum ' + acc + ' != ' + bytes.length + ' bytes'; break; }
          const bptr = api._malloc(bytes.length);
          const optr = api._malloc(pages * 4);
          const lptr = api._malloc(pages * 4);
          try {
            api.HEAPU8.set(bytes, bptr);
            new Uint32Array(api.HEAPU8.buffer, optr, pages).set(offs);
            new Uint32Array(api.HEAPU8.buffer, lptr, pages).set(lengths);
            if (api._ko_assemble_add_spine(bptr, bytes.length, pages, optr, lptr) < 0) {
              bad = 'assemble add spine failed for spine ' + sp.spine; break;
            }
          } finally {
            api._free(bptr); api._free(optr); api._free(lptr);
          }
          for (const t of (sp.toc || [])) {
            const r = withCString(t.title, (tp) => api._ko_assemble_add_toc(base, tp, t.localPage | 0));
            void r;
          }
          withCString(sp.fallbackName, (fp) => api._ko_assemble_add_fallback(base, fp, pages));
          base += pages;
          raw += bytes.length;
        }
        if (bad) { post(id, false, { error: bad }); break; }
        const total = api._ko_assemble_finish();
        if (total < 0) { post(id, false, { error: 'assemble finish failed' }); break; }
        // rawBytes is the UNCOMPRESSED container — header, metadata, chapters, index and records. It
        // used to be the sum of the page records, which made the UI divide by a number that excluded
        // everything but the records. recordBytes keeps the old figure as an assembly diagnostic.
        const rawBytes = api._ko_xtch_size();
        if (ev.data.xtcz) api._ko_xtcz_wrap();
        const p2 = api._ko_xtch_ptr();
        const sz = api._ko_xtch_size();
        const out = api.HEAPU8.slice(p2, p2 + sz);
        post(id, true, { pages: total, spinePages: base, recordBytes: raw,
                         xtcz: !!ev.data.xtcz, rawBytes,
                         bytes: out.buffer }, [out.buffer]);
        break;
      }

      case 'exportBook': {
        // whole-book export with the current spec; 1-bit XTC or 2-bit XTCH per
        // mode (xtcz=true wraps in XTZ4/LZ4); progress posts (no op id)
        // A background warm may be driving the engine: it shares the C export
        // buffer, so supersede it and wait for it to stop (it polls the token
        // between spines and aborts within a few yields).
        if (foregroundExportRunning) {
          post(id, false, { error: 'export already running' });
          break;
        }
        // §1: from here to the finally, the engine state is frozen: any mutating command that arrives
        // in a yield window is rejected rather than silently changing what the file contains.
        foregroundExportRunning = true;
        // §1 of the 1.5 audit: the try must begin HERE. It used to begin after the setup, so a throw
        // from stopWarmBeforeMutation / applySpecIfChanged / the export-mode setup left the lock set
        // forever — every later mutation then rejected for the life of the worker.
        let res;
        try {
        // §2: same fail-closed wait as any other mutation (it also drops the superseded warm bytes)
        await stopWarmBeforeMutation();
        // The tone depth must follow the MODE, not whatever spec happens to be
        // applied: a 1-bit page has to be dithered straight to 2 tones, and if the
        // spec still says 4 the writer packs a 4-level page into one plane (the
        // host CLI has always done this; the worker relied on the caller passing
        // imageToneDepth, which any new export path could forget).
        // §3 of the 1.3 audit: the snapshot is applied AFTER the lock is held, so the settings the
        // file is built from are exactly the settings the caller sent with this one message.
        if (ev.data.spec) await applySpecIfChanged(ev.data.spec);
        const exportMode = ev.data.mode === 0 ? 0 : 1;
        api._ko_export_set_mode(exportMode);
        const exportDepth = exportMode === 0 ? 2 : 4;
        api._ko_set_image_tone_depth(exportDepth);
        if (currentSpec) currentSpec.imageToneDepth = exportDepth;
        const opts = { xtcz: !!ev.data.xtcz };
          // exportWholeBook owns its own abort cleanup on every abnormal exit (cancel, spine
          // failure, finish failure), so there is no catch here: one owner for cleanup.
          invalidateSection();
          res = await exportWholeBook(opts, (spine, ofSpines, pages) => {
            self.postMessage({ progress: true, spine, ofSpines, pages });
          });
        // the export loop built+rendered every spine through the engine, so
        // per-spine engine state is undefined afterwards — force a rebuild on
        // the next engine render (keeps page flips after export safe)
        } finally {
          foregroundExportRunning = false;
        }
        invalidateEngine();
        // hand the finished bytes to the app as a transferable for download
        const tx = takeTransferBuffer(res.file)     // §2: no full-file copy;
        post(id, true, { file: tx, mode: ev.data.mode === 0 ? 0 : 1,
                         pages: res.pages, spines: res.spines,
                         xtcz: res.xtcz, rawBytes: res.rawBytes,
                         // diagnostic: per-spine ms and the preflight cost, if any. Storing these
                         // in the worker alone was useless — nothing could ask for them.
                         spineTimes: LAST_EXPORT.spines, preflight: LAST_EXPORT.preflight }, [tx]);
        break;
      }

      case 'pageCount': {
        post(id, true, { pages: currentPages, spine: currentSpine });
        break;
      }

      case 'stats': {
        post(id, true, {
          lastExport: LAST_EXPORT,
          times: cmdTimes,
          counters: COUNTERS,
          frameCache: { entries: frameCache.size, bytes: frameCacheBytes, budget: FRAME_CACHE_BUDGET },
          heapBytes: api ? api.HEAPU8.buffer.byteLength : 0,   // wasm linear memory high-water mark
          storageBytes: api ? api._ko_storage_bytes() : 0,     // what HalStorage is actually holding
          engine: { spine: currentSpine, pages: currentPages, builtKey, fontStamp },
          keys: { layout: currentSpec ? layoutKey(currentSpec) : null,
                  render: currentSpec ? renderKey(currentSpec) : null },
          warmRunning,
        });
        break;
      }

      default:
        post(id, false, { error: 'unknown cmd ' + cmd });
    }
  } catch (e) {
    // A throw here usually means the wasm runtime aborted (OOM / bad_alloc
    // under -fno-exceptions). The engine is poisoned after an abort — flag
    // fatal so the app respawns the worker instead of retrying a dead engine.
    const msg = String(e && e.message || e);
    const fatal = /abort|runtime|out of memory|allocation/i.test(msg);
    try { post(id, false, { error: msg, fatal }); } catch (_) {}
    if (fatal) {
      // give the reply a moment to flush, then die loudly (app respawns)
      setTimeout(() => { throw new Error('engine aborted: ' + msg); }, 0);
    }
  }
};
